import os, re
links = [
    ("千问","https://www.qianwen.com/chat"),
    ("GitHub","https://github.com/"),
    ("光鸭云盘","https://www.guangyapan.com/#/home/all"),
    ("菜鸟工具","https://www.jyshare.com/"),
    ("中国教育考试网","https://ncre.neea.edu.cn/"),
    ("软考","https://www.ruankao.org.cn/"),
    ("W3School","https://www.w3school.com.cn/"),
    ("光鸭资源设","https://www.guangya.cc/"),
    ("校园知问","https://xiaobaocampus.com/"),
    ("赛博丐帮","https://poorgpt.com/"),
    ("觅知网","https://www.51miz.com/"),
    ("调色板","https://color.adobe.com/cn/create/color-wheel"),
    ("aboutppt","https://www.aboutppt.com/"),
    ("即时移除背景","https://remove-bg.io/zh-CN/"),
    ("佐糖AI","https://picwish.cn/remove-background"),
    ("阿里巴巴矢量图标库","https://www.iconfont.cn/"),
    ("优设字体","https://hao.uisdc.com/font/"),
    ("猫啃网","https://www.maoken.com/"),
    ("key","key.html"),
    ("豆包","https://www.doubao.com/chat/"),
    ("抖音","https://www.douyin.com/"),
    ("Outlook","https://outlook.live.com/calendar"),
    ("AI去水印","https://magiceraser.org/"),
    ("优智云家","https://go.kiwik.cn/"),
    ("@@@@","#"),
]
print(f"links count: {len(links)}")